export interface RawQuestion {
  id: string;
  topic: string;
  difficulty: "teen" | "child";
  question: string;
  option_a: string;
  option_b: string;
  option_c: string;
  option_d: string;
  correct: "a" | "b" | "c" | "d";
}

export const QUESTIONS: RawQuestion[] = [

  // ═══════════════════════════════════════════════════════════════════
  // TEEN / ADULT QUESTIONS
  // ═══════════════════════════════════════════════════════════════════

  // ─── Movies (25) ────────────────────────────────────────────────────
  { id: "mov_01", topic: "movies", difficulty: "teen",
    question: "In 'The Shawshank Redemption' (1994), what tool does Andy Dufresne use to slowly tunnel through his cell wall over 19 years?",
    option_a: "A spoon", option_b: "A chisel", option_c: "A rock hammer", option_d: "A nail file", correct: "c" },
  { id: "mov_02", topic: "movies", difficulty: "teen",
    question: "Which director made both 'Blade Runner' (1982) and 'Gladiator' (2000)?",
    option_a: "James Cameron", option_b: "Ridley Scott", option_c: "Christopher Nolan", option_d: "Steven Spielberg", correct: "b" },
  { id: "mov_03", topic: "movies", difficulty: "teen",
    question: "What fictional African country is home to Black Panther's kingdom in the MCU?",
    option_a: "Genosha", option_b: "Latveria", option_c: "Sokovia", option_d: "Wakanda", correct: "d" },
  { id: "mov_04", topic: "movies", difficulty: "teen",
    question: "In 'Interstellar' (2014), the crew visits several planets after the wormhole. Which do they reach first?",
    option_a: "Edmunds' planet", option_b: "Mann's planet", option_c: "Miller's planet", option_d: "Saturn's moon", correct: "c" },
  { id: "mov_05", topic: "movies", difficulty: "teen",
    question: "Who delivers the line 'You can't handle the truth!' in 'A Few Good Men'?",
    option_a: "Tom Hanks", option_b: "Jack Nicholson", option_c: "Al Pacino", option_d: "Kevin Bacon", correct: "b" },
  { id: "mov_06", topic: "movies", difficulty: "teen",
    question: "Which film features the line 'Elementary, my dear Watson' — and is notable for the phrase actually NOT appearing in Arthur Conan Doyle's original stories?",
    option_a: "The Hound of the Baskervilles (1939)", option_b: "Sherlock Holmes (2009)", option_c: "Without a Clue (1988)", option_d: "Young Sherlock Holmes (1985)", correct: "a" },
  { id: "mov_07", topic: "movies", difficulty: "teen",
    question: "The 1994 film 'Forrest Gump' mentions life is like a box of what?",
    option_a: "Surprises", option_b: "Chocolates", option_c: "Wishes", option_d: "Puzzles", correct: "b" },
  { id: "mov_08", topic: "movies", difficulty: "teen",
    question: "What was the name of the island where the dinosaurs lived in the original 'Jurassic Park' (1993)?",
    option_a: "Isla Sorna", option_b: "Isla Nublar", option_c: "Isla Muer", option_d: "Isla Cabra", correct: "b" },
  { id: "mov_09", topic: "movies", difficulty: "teen",
    question: "In 'The Matrix' (1999), Neo is offered which two pills — one to stay in the simulation, one to see the truth?",
    option_a: "Red and Blue", option_b: "Black and White", option_c: "Green and Yellow", option_d: "Purple and Orange", correct: "a" },
  { id: "mov_10", topic: "movies", difficulty: "teen",
    question: "Which animated film features the song 'Let It Go' and is set in the fictional kingdom of Arendelle?",
    option_a: "Brave", option_b: "Moana", option_c: "Frozen", option_d: "Tangled", correct: "c" },
  { id: "mov_11", topic: "movies", difficulty: "teen",
    question: "In 'Fight Club' (1999), what is the first rule of Fight Club?",
    option_a: "No weapons", option_b: "No women allowed", option_c: "You do not talk about Fight Club", option_d: "One fight at a time", correct: "c" },
  { id: "mov_12", topic: "movies", difficulty: "teen",
    question: "Which 1993 film follows an arrogant weatherman doomed to relive the same day over and over?",
    option_a: "12 Monkeys", option_b: "Groundhog Day", option_c: "Memento", option_d: "Edge of Tomorrow", correct: "b" },
  { id: "mov_13", topic: "movies", difficulty: "teen",
    question: "What spaceship do Han Solo and Chewbacca fly in the Star Wars universe?",
    option_a: "The Tantive IV", option_b: "The Executor", option_c: "The Millennium Falcon", option_d: "The Ghost", correct: "c" },
  { id: "mov_14", topic: "movies", difficulty: "teen",
    question: "In 'Parasite' (2019), where does the Park family keep their safe in the basement?",
    option_a: "Behind a painting", option_b: "Under the floor", option_c: "Behind a bookshelf", option_d: "Inside a wardrobe", correct: "c" },
  { id: "mov_15", topic: "movies", difficulty: "teen",
    question: "Which actress played Katniss Everdeen in 'The Hunger Games' franchise?",
    option_a: "Shailene Woodley", option_b: "Emma Watson", option_c: "Saoirse Ronan", option_d: "Jennifer Lawrence", correct: "d" },
  { id: "mov_16", topic: "movies", difficulty: "teen",
    question: "The film 'Everything Everywhere All at Once' won Best Picture at which Academy Awards ceremony?",
    option_a: "2021 (93rd)", option_b: "2022 (94th)", option_c: "2023 (95th)", option_d: "2024 (96th)", correct: "c" },
  { id: "mov_17", topic: "movies", difficulty: "teen",
    question: "In 'Back to the Future', what speed must the DeLorean reach to activate time travel?",
    option_a: "55 mph", option_b: "77 mph", option_c: "88 mph", option_d: "100 mph", correct: "c" },
  { id: "mov_18", topic: "movies", difficulty: "teen",
    question: "Which director is known for 'Pulp Fiction', 'Kill Bill', and 'Once Upon a Time in Hollywood'?",
    option_a: "David Fincher", option_b: "Quentin Tarantino", option_c: "Joel Coen", option_d: "Paul Thomas Anderson", correct: "b" },
  { id: "mov_19", topic: "movies", difficulty: "teen",
    question: "'Spirited Away' (2001) is a Japanese animated film directed by whom?",
    option_a: "Makoto Shinkai", option_b: "Mamoru Hosoda", option_c: "Satoshi Kon", option_d: "Hayao Miyazaki", correct: "d" },
  { id: "mov_20", topic: "movies", difficulty: "teen",
    question: "In 'The Silence of the Lambs', what does Hannibal Lecter claim to have eaten with fava beans?",
    option_a: "A senator's aide", option_b: "A census taker's liver", option_c: "A police officer's heart", option_d: "A nurse's kidney", correct: "b" },
  { id: "mov_21", topic: "movies", difficulty: "teen",
    question: "Which film was the first feature-length animated movie ever released by Walt Disney Productions?",
    option_a: "Bambi", option_b: "Pinocchio", option_c: "Snow White and the Seven Dwarfs", option_d: "Fantasia", correct: "c" },
  { id: "mov_22", topic: "movies", difficulty: "teen",
    question: "What is the name of the bar in 'Cheers', the long-running American sitcom later adapted into films?",
    option_a: "Moe's Tavern", option_b: "Paddy's Pub", option_c: "The Regal Beagle", option_d: "Cheers (the bar is named Cheers)", correct: "d" },
  { id: "mov_23", topic: "movies", difficulty: "teen",
    question: "In 'Arrival' (2016), what triggers the alien heptapods to leave Earth?",
    option_a: "Humans decode their weapon and use it", option_b: "Louise reveals the future to the Chinese general", option_c: "The UN votes to attack", option_d: "A nuclear weapon is detonated near their ship", correct: "b" },
  { id: "mov_24", topic: "movies", difficulty: "teen",
    question: "Which actor played Iron Man / Tony Stark across the Marvel Cinematic Universe films?",
    option_a: "Chris Evans", option_b: "Mark Ruffalo", option_c: "Robert Downey Jr.", option_d: "Benedict Cumberbatch", correct: "c" },
  { id: "mov_25", topic: "movies", difficulty: "teen",
    question: "In Kubrick's '2001: A Space Odyssey', what does HAL 9000 refuse to do when astronaut Dave Bowman asks?",
    option_a: "Plot a return course to Earth", option_b: "Open the pod bay doors", option_c: "Display the mission briefing", option_d: "Wake the crew from hibernation", correct: "b" },

  // ─── Forestry (25) ───────────────────────────────────────────────────
  { id: "for_01", topic: "forestry", difficulty: "teen",
    question: "What is the process by which trees release water vapour through their leaves called?",
    option_a: "Photosynthesis", option_b: "Respiration", option_c: "Transpiration", option_d: "Osmosis", correct: "c" },
  { id: "for_02", topic: "forestry", difficulty: "teen",
    question: "Which layer of a tree trunk transports water and minerals upward from the roots?",
    option_a: "Heartwood", option_b: "Bark (phloem)", option_c: "Cambium", option_d: "Xylem (sapwood)", correct: "d" },
  { id: "for_03", topic: "forestry", difficulty: "teen",
    question: "The Amazon rainforest spans primarily across which country?",
    option_a: "Colombia", option_b: "Peru", option_c: "Venezuela", option_d: "Brazil", correct: "d" },
  { id: "for_04", topic: "forestry", difficulty: "teen",
    question: "What forestry term describes harvesting ALL trees in an area at once?",
    option_a: "Selective logging", option_b: "Clear-cutting", option_c: "Coppicing", option_d: "Shelterwood harvesting", correct: "b" },
  { id: "for_05", topic: "forestry", difficulty: "teen",
    question: "Underground fungal networks linking forest tree roots are nicknamed what?",
    option_a: "The root web", option_b: "The mycelium grid", option_c: "The wood wide web", option_d: "The fungal floor", correct: "c" },
  { id: "for_06", topic: "forestry", difficulty: "teen",
    question: "Which tree produces acorns as its fruit?",
    option_a: "Beech", option_b: "Chestnut", option_c: "Oak", option_d: "Elm", correct: "c" },
  { id: "for_07", topic: "forestry", difficulty: "teen",
    question: "What is the term for a forest management technique where trees are cut near the ground to encourage regrowth of multiple stems?",
    option_a: "Pollarding", option_b: "Coppicing", option_c: "Thinning", option_d: "Crown reduction", correct: "b" },
  { id: "for_08", topic: "forestry", difficulty: "teen",
    question: "The Daintree Rainforest, one of the world's oldest tropical rainforests, is located in which country?",
    option_a: "Papua New Guinea", option_b: "Indonesia", option_c: "New Zealand", option_d: "Australia", correct: "d" },
  { id: "for_09", topic: "forestry", difficulty: "teen",
    question: "What is the scientific name for the photosynthesis-absorbing green pigment in leaves?",
    option_a: "Carotene", option_b: "Chlorophyll", option_c: "Anthocyanin", option_d: "Xanthophyll", correct: "b" },
  { id: "for_10", topic: "forestry", difficulty: "teen",
    question: "Which tree holds the record for being the tallest living tree species on Earth?",
    option_a: "Giant Sequoia", option_b: "Douglas Fir", option_c: "Coast Redwood", option_d: "Sitka Spruce", correct: "c" },
  { id: "for_11", topic: "forestry", difficulty: "teen",
    question: "In forest ecology, what term describes a plant that grows on another plant (but doesn't harm it), like many orchids and ferns?",
    option_a: "Parasite", option_b: "Epiphyte", option_c: "Saprophyte", option_d: "Lithophyte", correct: "b" },
  { id: "for_12", topic: "forestry", difficulty: "teen",
    question: "What percentage of the Earth's land surface is covered by forests?",
    option_a: "About 11%", option_b: "About 21%", option_c: "About 31%", option_d: "About 41%", correct: "c" },
  { id: "for_13", topic: "forestry", difficulty: "teen",
    question: "The taiga (boreal forest) is the world's largest land biome. It is predominantly found in which region?",
    option_a: "Central Africa", option_b: "Northern Russia, Canada, and Scandinavia", option_c: "The Himalayas", option_d: "Southern South America", correct: "b" },
  { id: "for_14", topic: "forestry", difficulty: "teen",
    question: "What chemical compound gives autumn leaves their red and purple colours?",
    option_a: "Chlorophyll", option_b: "Carotene", option_c: "Tannin", option_d: "Anthocyanin", correct: "d" },
  { id: "for_15", topic: "forestry", difficulty: "teen",
    question: "Which ancient tree, found in California's White Mountains, is considered one of the oldest individual living organisms on Earth?",
    option_a: "A coast redwood", option_b: "A bristlecone pine", option_c: "A giant sequoia", option_d: "A baobab", correct: "b" },
  { id: "for_16", topic: "forestry", difficulty: "teen",
    question: "Deforestation contributes to climate change primarily by releasing what gas?",
    option_a: "Methane", option_b: "Nitrous oxide", option_c: "Carbon dioxide", option_d: "Ozone", correct: "c" },
  { id: "for_17", topic: "forestry", difficulty: "teen",
    question: "What is the name of the zone in a forest between the full-canopy forest and open land, known for high biodiversity?",
    option_a: "The edge effect zone", option_b: "The ecotone", option_c: "The understory", option_d: "The riparian zone", correct: "b" },
  { id: "for_18", topic: "forestry", difficulty: "teen",
    question: "The rubber tree (Hevea brasiliensis) is native to which region?",
    option_a: "Central Africa", option_b: "Southeast Asia", option_c: "The Amazon Basin", option_d: "Central America", correct: "c" },
  { id: "for_19", topic: "forestry", difficulty: "teen",
    question: "What is silviculture?",
    option_a: "The study of silver deposits in forest soil", option_b: "The art and science of growing and cultivating forests", option_c: "The practice of carving wood for art", option_d: "The measurement of tree age using rings", correct: "b" },
  { id: "for_20", topic: "forestry", difficulty: "teen",
    question: "Dendrochronology is the scientific method of dating trees and timber by analysing what?",
    option_a: "Leaf shape", option_b: "Root depth", option_c: "Annual growth rings", option_d: "Bark texture", correct: "c" },
  { id: "for_21", topic: "forestry", difficulty: "teen",
    question: "Which tree is known as the 'pioneer species' because it is often the first to colonise disturbed land after a fire or clearance?",
    option_a: "Oak", option_b: "Silver birch", option_c: "Yew", option_d: "Beech", correct: "b" },
  { id: "for_22", topic: "forestry", difficulty: "teen",
    question: "What does a forest's 'canopy layer' refer to?",
    option_a: "The root network underground", option_b: "The layer of moss and lichens on the forest floor", option_c: "The topmost layer of overlapping tree crowns", option_d: "The mid-level shrub layer", correct: "c" },
  { id: "for_23", topic: "forestry", difficulty: "teen",
    question: "The seeds of which tree spin like helicopter rotors and are called 'samaras' or 'helicopters' by children?",
    option_a: "Oak", option_b: "Ash", option_c: "Maple", option_d: "Walnut", correct: "c" },
  { id: "for_24", topic: "forestry", difficulty: "teen",
    question: "In forestry, what does 'FSC' stand for?",
    option_a: "Federal Silviculture Council", option_b: "Forest Stewardship Council", option_c: "Foundation for Sustainable Cutting", option_d: "Forest Species Catalogue", correct: "b" },
  { id: "for_25", topic: "forestry", difficulty: "teen",
    question: "Which ancient Japanese practice involves mindful immersion in a forest environment for health benefits?",
    option_a: "Ikebana", option_b: "Wabi-sabi", option_c: "Shinrin-yoku", option_d: "Kintsugi", correct: "c" },

  // ─── Travel (25) ─────────────────────────────────────────────────────
  { id: "trv_01", topic: "travel", difficulty: "teen",
    question: "The ancient city of Petra, carved into rose-red sandstone cliffs, is located in which country?",
    option_a: "Saudi Arabia", option_b: "Egypt", option_c: "Jordan", option_d: "Israel", correct: "c" },
  { id: "trv_02", topic: "travel", difficulty: "teen",
    question: "The Trans-Siberian Railway, the world's longest, runs from Moscow to which Pacific port city?",
    option_a: "Irkutsk", option_b: "Novosibirsk", option_c: "Vladivostok", option_d: "Yakutsk", correct: "c" },
  { id: "trv_03", topic: "travel", difficulty: "teen",
    question: "In which Southeast Asian city would you find the famous street food market of Jalan Alor?",
    option_a: "Bangkok", option_b: "Kuala Lumpur", option_c: "Singapore", option_d: "Ho Chi Minh City", correct: "b" },
  { id: "trv_04", topic: "travel", difficulty: "teen",
    question: "The Northern Lights are most reliably visible from which of these destinations?",
    option_a: "Edinburgh, Scotland", option_b: "Helsinki city centre", option_c: "Tromsø, Norway", option_d: "Copenhagen, Denmark", correct: "c" },
  { id: "trv_05", topic: "travel", difficulty: "teen",
    question: "Which island chain in Indonesia is home to the Komodo dragon in the wild?",
    option_a: "Bali", option_b: "The Lesser Sunda Islands (incl. Komodo Island)", option_c: "Borneo", option_d: "Java", correct: "b" },
  { id: "trv_06", topic: "travel", difficulty: "teen",
    question: "The ancient Incan citadel of Machu Picchu sits at approximately what elevation?",
    option_a: "1,200 m (3,900 ft)", option_b: "2,430 m (7,970 ft)", option_c: "3,800 m (12,500 ft)", option_d: "5,200 m (17,000 ft)", correct: "b" },
  { id: "trv_07", topic: "travel", difficulty: "teen",
    question: "What is the deepest lake in the world, holding about 20% of the world's unfrozen fresh water?",
    option_a: "Lake Superior", option_b: "Lake Titicaca", option_c: "Caspian Sea", option_d: "Lake Baikal", correct: "d" },
  { id: "trv_08", topic: "travel", difficulty: "teen",
    question: "The Camino de Santiago is a famous pilgrimage route ending in which city?",
    option_a: "Pamplona", option_b: "Santiago de Compostela", option_c: "Seville", option_d: "Lisbon", correct: "b" },
  { id: "trv_09", topic: "travel", difficulty: "teen",
    question: "Which country has the most UNESCO World Heritage Sites?",
    option_a: "France", option_b: "India", option_c: "China", option_d: "Italy", correct: "d" },
  { id: "trv_10", topic: "travel", difficulty: "teen",
    question: "The Serengeti National Park, famous for the Great Migration of wildebeest, is located in which country?",
    option_a: "Kenya", option_b: "South Africa", option_c: "Tanzania", option_d: "Botswana", correct: "c" },
  { id: "trv_11", topic: "travel", difficulty: "teen",
    question: "What is the name of the iconic long-distance hiking trail running the length of New Zealand's South Island?",
    option_a: "Te Araroa Trail", option_b: "The Routeburn Track", option_c: "The Milford Track", option_d: "The Heaphy Track", correct: "a" },
  { id: "trv_12", topic: "travel", difficulty: "teen",
    question: "The Maldives is known for being the world's lowest-lying country. What threat does this pose?",
    option_a: "Volcanic eruption risk", option_b: "Submersion due to rising sea levels", option_c: "Desert expansion", option_d: "Permafrost collapse", correct: "b" },
  { id: "trv_13", topic: "travel", difficulty: "teen",
    question: "Which country has more natural lakes than any other in the world?",
    option_a: "Russia", option_b: "Finland", option_c: "Canada", option_d: "Norway", correct: "c" },
  { id: "trv_14", topic: "travel", difficulty: "teen",
    question: "The Blue Mosque (Sultan Ahmed Mosque) is a landmark in which city?",
    option_a: "Tehran", option_b: "Cairo", option_c: "Istanbul", option_d: "Dubai", correct: "c" },
  { id: "trv_15", topic: "travel", difficulty: "teen",
    question: "Angkor Wat, the world's largest religious monument, is located in which country?",
    option_a: "Vietnam", option_b: "Thailand", option_c: "Myanmar", option_d: "Cambodia", correct: "d" },
  { id: "trv_16", topic: "travel", difficulty: "teen",
    question: "Which city is divided by the famous Bosphorus strait, straddling two continents?",
    option_a: "Athens", option_b: "Istanbul", option_c: "Alexandria", option_d: "Tbilisi", correct: "b" },
  { id: "trv_17", topic: "travel", difficulty: "teen",
    question: "The Amalfi Coast, a famous scenic drive, is located in which Italian region?",
    option_a: "Tuscany", option_b: "Sicily", option_c: "Sardinia", option_d: "Campania", correct: "d" },
  { id: "trv_18", topic: "travel", difficulty: "teen",
    question: "What is the name of the world's largest coral reef system?",
    option_a: "The Mesoamerican Barrier Reef", option_b: "The Great Barrier Reef", option_c: "The New Caledonia Barrier Reef", option_d: "The Andros Barrier Reef", correct: "b" },
  { id: "trv_19", topic: "travel", difficulty: "teen",
    question: "Reykjavik is the capital of Iceland. Approximately how many people live in all of Iceland?",
    option_a: "About 150,000", option_b: "About 370,000", option_c: "About 700,000", option_d: "About 1.2 million", correct: "b" },
  { id: "trv_20", topic: "travel", difficulty: "teen",
    question: "The Inca Trail trek culminates at which ancient site?",
    option_a: "Cusco", option_b: "Chan Chan", option_c: "Machu Picchu", option_d: "Chichen Itza", correct: "c" },
  { id: "trv_21", topic: "travel", difficulty: "teen",
    question: "Which ocean would you cross when flying non-stop from London to New York?",
    option_a: "The Arctic Ocean", option_b: "The North Atlantic Ocean", option_c: "The Pacific Ocean", option_d: "The North Sea", correct: "b" },
  { id: "trv_22", topic: "travel", difficulty: "teen",
    question: "The Hagia Sophia, originally a cathedral then a mosque and now a mosque again, is in which city?",
    option_a: "Athens", option_b: "Rome", option_c: "Jerusalem", option_d: "Istanbul", correct: "d" },
  { id: "trv_23", topic: "travel", difficulty: "teen",
    question: "Patagonia, a popular destination for hiking and wilderness travel, spans parts of which two countries?",
    option_a: "Brazil and Uruguay", option_b: "Chile and Argentina", option_c: "Bolivia and Peru", option_d: "Colombia and Ecuador", correct: "b" },
  { id: "trv_24", topic: "travel", difficulty: "teen",
    question: "The famous Silk Road historically connected China to which region?",
    option_a: "West Africa", option_b: "The Mediterranean and Europe", option_c: "The Indian subcontinent only", option_d: "Japan and Korea", correct: "b" },
  { id: "trv_25", topic: "travel", difficulty: "teen",
    question: "Which country is made up of 17,508 islands, making it the world's largest archipelago nation?",
    option_a: "Philippines", option_b: "Japan", option_c: "Indonesia", option_d: "Malaysia", correct: "c" },

  // ─── Geography (25) ──────────────────────────────────────────────────
  { id: "geo_01", topic: "geography", difficulty: "teen",
    question: "What is the only country in the world that borders both the Atlantic and Indian Oceans?",
    option_a: "Brazil", option_b: "Angola", option_c: "South Africa", option_d: "Mozambique", correct: "c" },
  { id: "geo_02", topic: "geography", difficulty: "teen",
    question: "The Mariana Trench — the deepest point on Earth — is in which ocean?",
    option_a: "Atlantic", option_b: "Indian", option_c: "Arctic", option_d: "Pacific", correct: "d" },
  { id: "geo_03", topic: "geography", difficulty: "teen",
    question: "Which river flows through the most countries?",
    option_a: "The Nile", option_b: "The Amazon", option_c: "The Danube", option_d: "The Congo", correct: "c" },
  { id: "geo_04", topic: "geography", difficulty: "teen",
    question: "What percentage of the Earth's surface is covered by water?",
    option_a: "51%", option_b: "61%", option_c: "71%", option_d: "81%", correct: "c" },
  { id: "geo_05", topic: "geography", difficulty: "teen",
    question: "Mount Kilimanjaro is the highest peak on which continent?",
    option_a: "South America", option_b: "Asia", option_c: "Australia", option_d: "Africa", correct: "d" },
  { id: "geo_06", topic: "geography", difficulty: "teen",
    question: "What is the largest desert on Earth (by area)?",
    option_a: "The Gobi Desert", option_b: "The Sahara Desert", option_c: "The Antarctic Desert", option_d: "The Arabian Desert", correct: "c" },
  { id: "geo_07", topic: "geography", difficulty: "teen",
    question: "The Ring of Fire, a zone of frequent earthquakes and volcanic eruptions, encircles which ocean?",
    option_a: "The Atlantic", option_b: "The Indian", option_c: "The Pacific", option_d: "The Arctic", correct: "c" },
  { id: "geo_08", topic: "geography", difficulty: "teen",
    question: "Which is the world's longest river?",
    option_a: "The Amazon", option_b: "The Nile", option_c: "The Yangtze", option_d: "The Mississippi", correct: "b" },
  { id: "geo_09", topic: "geography", difficulty: "teen",
    question: "What is the capital of Australia?",
    option_a: "Sydney", option_b: "Melbourne", option_c: "Perth", option_d: "Canberra", correct: "d" },
  { id: "geo_10", topic: "geography", difficulty: "teen",
    question: "Which country has the world's longest coastline?",
    option_a: "Russia", option_b: "Australia", option_c: "Norway", option_d: "Canada", correct: "d" },
  { id: "geo_11", topic: "geography", difficulty: "teen",
    question: "The Sahara Desert spans approximately how many African countries?",
    option_a: "5", option_b: "8", option_c: "11", option_d: "14", correct: "c" },
  { id: "geo_12", topic: "geography", difficulty: "teen",
    question: "Which two continents does the Ural mountain range traditionally separate?",
    option_a: "Asia and Africa", option_b: "Europe and Asia", option_c: "Europe and North America", option_d: "North Asia and South Asia", correct: "b" },
  { id: "geo_13", topic: "geography", difficulty: "teen",
    question: "The Dead Sea, the world's lowest point on land, borders which countries?",
    option_a: "Israel, Jordan, and the Palestinian West Bank", option_b: "Egypt and Israel", option_c: "Syria and Lebanon", option_d: "Jordan and Saudi Arabia", correct: "a" },
  { id: "geo_14", topic: "geography", difficulty: "teen",
    question: "Which country is entirely landlocked within South Africa?",
    option_a: "Swaziland (Eswatini)", option_b: "Lesotho", option_c: "Both Swaziland and Lesotho", option_d: "Zimbabwe", correct: "b" },
  { id: "geo_15", topic: "geography", difficulty: "teen",
    question: "The Caspian Sea is technically a lake. Which country has the longest coastline along it?",
    option_a: "Russia", option_b: "Kazakhstan", option_c: "Iran", option_d: "Azerbaijan", correct: "b" },
  { id: "geo_16", topic: "geography", difficulty: "teen",
    question: "Which is the world's smallest country by land area?",
    option_a: "Monaco", option_b: "San Marino", option_c: "Liechtenstein", option_d: "Vatican City", correct: "d" },
  { id: "geo_17", topic: "geography", difficulty: "teen",
    question: "The Great Rift Valley, a massive geological formation, runs through which continent?",
    option_a: "Asia", option_b: "Australia", option_c: "Africa", option_d: "South America", correct: "c" },
  { id: "geo_18", topic: "geography", difficulty: "teen",
    question: "Which South American country has the most Spanish speakers?",
    option_a: "Argentina", option_b: "Colombia", option_c: "Mexico (in North America)", option_d: "Colombia", correct: "b" },
  { id: "geo_19", topic: "geography", difficulty: "teen",
    question: "What is the name of the narrow strip of land connecting North and South America?",
    option_a: "The Yucatán Isthmus", option_b: "The Isthmus of Panama", option_c: "The Darien Gap", option_d: "The Central American Bridge", correct: "b" },
  { id: "geo_20", topic: "geography", difficulty: "teen",
    question: "Lake Titicaca, the highest navigable lake in the world, straddles the border of which two countries?",
    option_a: "Peru and Ecuador", option_b: "Bolivia and Chile", option_c: "Peru and Bolivia", option_d: "Argentina and Chile", correct: "c" },
  { id: "geo_21", topic: "geography", difficulty: "teen",
    question: "Which ocean is the smallest of the world's five oceans?",
    option_a: "Indian", option_b: "Southern", option_c: "Arctic", option_d: "Atlantic", correct: "c" },
  { id: "geo_22", topic: "geography", difficulty: "teen",
    question: "The Cape of Good Hope is at the southern tip of which country?",
    option_a: "Namibia", option_b: "Angola", option_c: "South Africa", option_d: "Mozambique", correct: "c" },
  { id: "geo_23", topic: "geography", difficulty: "teen",
    question: "Greenland is the world's largest island. It is a territory of which country?",
    option_a: "Norway", option_b: "Iceland", option_c: "Canada", option_d: "Denmark", correct: "d" },
  { id: "geo_24", topic: "geography", difficulty: "teen",
    question: "The Amazon River discharges into which ocean?",
    option_a: "The Pacific", option_b: "The Caribbean Sea", option_c: "The Atlantic", option_d: "The Gulf of Mexico", correct: "c" },
  { id: "geo_25", topic: "geography", difficulty: "teen",
    question: "Which mountain range includes the Himalaya, Karakoram, Hindu Kush, and Pamir ranges collectively?",
    option_a: "The Asian Highlands", option_b: "The Trans-Himalayan Ranges", option_c: "The Hindu-Kush System", option_d: "The Greater Himalayas", correct: "b" },

  // ─── Philosophy (25) ─────────────────────────────────────────────────
  { id: "phi_01", topic: "philosophy", difficulty: "teen",
    question: "Plato's 'Allegory of the Cave' — describing prisoners who mistake shadows for reality — appears in which work?",
    option_a: "The Apology", option_b: "Phaedo", option_c: "The Republic", option_d: "The Symposium", correct: "c" },
  { id: "phi_02", topic: "philosophy", difficulty: "teen",
    question: "Which philosopher wrote 'Cogito, ergo sum' ('I think, therefore I am')?",
    option_a: "Immanuel Kant", option_b: "René Descartes", option_c: "John Locke", option_d: "David Hume", correct: "b" },
  { id: "phi_03", topic: "philosophy", difficulty: "teen",
    question: "Which philosopher introduced the 'categorical imperative' as a universal principle of morality?",
    option_a: "John Stuart Mill", option_b: "Friedrich Nietzsche", option_c: "Jeremy Bentham", option_d: "Immanuel Kant", correct: "d" },
  { id: "phi_04", topic: "philosophy", difficulty: "teen",
    question: "'The unexamined life is not worth living' is attributed to which philosopher?",
    option_a: "Aristotle", option_b: "Epicurus", option_c: "Socrates", option_d: "Plato", correct: "c" },
  { id: "phi_05", topic: "philosophy", difficulty: "teen",
    question: "The philosophical thought experiment 'Trolley Problem' explores which ethical concept?",
    option_a: "Virtue ethics", option_b: "Moral dilemmas and consequentialism vs deontology", option_c: "Social contract theory", option_d: "Existentialism", correct: "b" },
  { id: "phi_06", topic: "philosophy", difficulty: "teen",
    question: "Jean-Paul Sartre's existentialist phrase 'existence precedes essence' means what?",
    option_a: "Physical existence is more important than spiritual matters", option_b: "Humans define their own meaning rather than having a preset purpose", option_c: "Life has no meaning at all", option_d: "Essence of things precedes their physical existence", correct: "b" },
  { id: "phi_07", topic: "philosophy", difficulty: "teen",
    question: "Which ancient Greek philosopher was Plato's teacher and Aristotle's teacher's teacher?",
    option_a: "Thales", option_b: "Heraclitus", option_c: "Socrates", option_d: "Pythagoras", correct: "c" },
  { id: "phi_08", topic: "philosophy", difficulty: "teen",
    question: "What is 'Occam's Razor'?",
    option_a: "The idea that the most complex explanation is usually correct", option_b: "The principle that entities should not be multiplied beyond necessity (prefer the simplest explanation)", option_c: "The view that truth can only be known through religious texts", option_d: "A logical fallacy involving ad hominem attacks", correct: "b" },
  { id: "phi_09", topic: "philosophy", difficulty: "teen",
    question: "Which philosopher wrote 'Thus Spoke Zarathustra' and introduced the concept of the Übermensch?",
    option_a: "Arthur Schopenhauer", option_b: "Georg Hegel", option_c: "Friedrich Nietzsche", option_d: "Martin Heidegger", correct: "c" },
  { id: "phi_10", topic: "philosophy", difficulty: "teen",
    question: "Utilitarianism, the idea that the right action maximises overall happiness, is most associated with which philosophers?",
    option_a: "Kant and Hegel", option_b: "Bentham and Mill", option_c: "Locke and Rousseau", option_d: "Aristotle and Plato", correct: "b" },
  { id: "phi_11", topic: "philosophy", difficulty: "teen",
    question: "The 'Ship of Theseus' paradox explores which philosophical question?",
    option_a: "The existence of God", option_b: "Personal identity and persistence through change", option_c: "Free will vs determinism", option_d: "The nature of time", correct: "b" },
  { id: "phi_12", topic: "philosophy", difficulty: "teen",
    question: "Which philosopher described the 'state of nature' as 'nasty, brutish, and short' — arguing humans need a social contract?",
    option_a: "Jean-Jacques Rousseau", option_b: "John Locke", option_c: "Thomas Hobbes", option_d: "David Hume", correct: "c" },
  { id: "phi_13", topic: "philosophy", difficulty: "teen",
    question: "In Plato's philosophy, what are the 'Forms' or 'Ideas'?",
    option_a: "The physical objects we see around us", option_b: "Perfect abstract archetypes of which physical things are imperfect copies", option_c: "Gods who govern the universe", option_d: "Mathematical equations underlying reality", correct: "b" },
  { id: "phi_14", topic: "philosophy", difficulty: "teen",
    question: "Albert Camus described the absurd as the conflict between what?",
    option_a: "Good and evil", option_b: "Humans' search for meaning and the universe's silence/indifference", option_c: "Free will and fate", option_d: "Mind and body", correct: "b" },
  { id: "phi_15", topic: "philosophy", difficulty: "teen",
    question: "What is 'solipsism'?",
    option_a: "The belief that everything is made of one substance", option_b: "The view that only one's own mind is certain to exist", option_c: "The denial of free will", option_d: "The belief that God created the universe but doesn't intervene", correct: "b" },
  { id: "phi_16", topic: "philosophy", difficulty: "teen",
    question: "'I know that I know nothing' is a paraphrase associated with which philosopher?",
    option_a: "Plato", option_b: "Aristotle", option_c: "Socrates", option_d: "Diogenes", correct: "c" },
  { id: "phi_17", topic: "philosophy", difficulty: "teen",
    question: "John Rawls' 'veil of ignorance' thought experiment is a device for designing what?",
    option_a: "A perfect military strategy", option_b: "A fair and just society without knowing your place in it", option_c: "An optimal economic market", option_d: "A system of environmental laws", correct: "b" },
  { id: "phi_18", topic: "philosophy", difficulty: "teen",
    question: "Epistemology is the branch of philosophy concerned with what?",
    option_a: "Ethics and morality", option_b: "The nature of beauty", option_c: "The nature and scope of knowledge", option_d: "The existence of God", correct: "c" },
  { id: "phi_19", topic: "philosophy", difficulty: "teen",
    question: "Which philosopher argued that 'God is dead' — meaning that the Enlightenment had destroyed the foundations of traditional morality?",
    option_a: "Karl Marx", option_b: "Søren Kierkegaard", option_c: "Friedrich Nietzsche", option_d: "Bertrand Russell", correct: "c" },
  { id: "phi_20", topic: "philosophy", difficulty: "teen",
    question: "The 'Chinese Room' thought experiment was designed by John Searle to argue what?",
    option_a: "That Chinese philosophy is superior to Western philosophy", option_b: "That syntax (symbol manipulation) alone cannot produce genuine understanding or consciousness", option_c: "That machines can have feelings", option_d: "That language determines thought", correct: "b" },
  { id: "phi_21", topic: "philosophy", difficulty: "teen",
    question: "Stoicism, founded by Zeno of Citium, teaches that human happiness comes from what?",
    option_a: "Pleasure and the avoidance of pain", option_b: "Wealth and social status", option_c: "Virtue and control over one's own judgements and reactions", option_d: "Total detachment from all desires", correct: "c" },
  { id: "phi_22", topic: "philosophy", difficulty: "teen",
    question: "What does Aristotle's 'Golden Mean' refer to?",
    option_a: "The ideal monetary system", option_b: "The virtue found between two extremes (deficiency and excess)", option_c: "A mathematical ratio found in nature", option_d: "The perfect balance of the four humours", correct: "b" },
  { id: "phi_23", topic: "philosophy", difficulty: "teen",
    question: "Which 20th-century philosopher wrote 'Being and Time' (Sein und Zeit)?",
    option_a: "Jean-Paul Sartre", option_b: "Edmund Husserl", option_c: "Martin Heidegger", option_d: "Ludwig Wittgenstein", correct: "c" },
  { id: "phi_24", topic: "philosophy", difficulty: "teen",
    question: "The Socratic Method involves reaching truth through what process?",
    option_a: "Quiet meditation and personal reflection", option_b: "Reading ancient texts carefully", option_c: "Collaborative questioning and dialogue that exposes contradictions", option_d: "Mathematical proof and logic alone", correct: "c" },
  { id: "phi_25", topic: "philosophy", difficulty: "teen",
    question: "Simone de Beauvoir's 'The Second Sex' is a foundational text in which movement?",
    option_a: "Existentialism only", option_b: "Feminist philosophy and theory", option_c: "Marxist theory", option_d: "Phenomenology", correct: "b" },

  // ═══════════════════════════════════════════════════════════════════
  // CHILD QUESTIONS
  // ═══════════════════════════════════════════════════════════════════

  // ─── Animals (20) ────────────────────────────────────────────────────
  { id: "ani_01", topic: "animals", difficulty: "child",
    question: "What do you call a baby dog?",
    option_a: "A kitten", option_b: "A puppy", option_c: "A foal", option_d: "A cub", correct: "b" },
  { id: "ani_02", topic: "animals", difficulty: "child",
    question: "Which animal is known for its black and white stripes?",
    option_a: "A giraffe", option_b: "A tiger", option_c: "A zebra", option_d: "A leopard", correct: "c" },
  { id: "ani_03", topic: "animals", difficulty: "child",
    question: "What sound does a cow make?",
    option_a: "Moo", option_b: "Baa", option_c: "Oink", option_d: "Cluck", correct: "a" },
  { id: "ani_04", topic: "animals", difficulty: "child",
    question: "Which animal is the tallest in the world?",
    option_a: "An elephant", option_b: "A giraffe", option_c: "A horse", option_d: "A polar bear", correct: "b" },
  { id: "ani_05", topic: "animals", difficulty: "child",
    question: "Where do penguins live in the wild?",
    option_a: "The North Pole", option_b: "The Amazon rainforest", option_c: "The Antarctic and Southern Ocean", option_d: "The Sahara desert", correct: "c" },
  { id: "ani_06", topic: "animals", difficulty: "child",
    question: "What do caterpillars turn into?",
    option_a: "Beetles", option_b: "Butterflies or moths", option_c: "Dragonflies", option_d: "Bees", correct: "b" },
  { id: "ani_07", topic: "animals", difficulty: "child",
    question: "Which animal has a pouch to carry its baby?",
    option_a: "A rabbit", option_b: "A kangaroo", option_c: "A deer", option_d: "A wolf", correct: "b" },
  { id: "ani_08", topic: "animals", difficulty: "child",
    question: "How many legs does a spider have?",
    option_a: "6", option_b: "10", option_c: "4", option_d: "8", correct: "d" },
  { id: "ani_09", topic: "animals", difficulty: "child",
    question: "Which animal is famous for changing its colour to blend in?",
    option_a: "A crocodile", option_b: "A chameleon", option_c: "A frog", option_d: "A lizard", correct: "b" },
  { id: "ani_10", topic: "animals", difficulty: "child",
    question: "What is the fastest land animal?",
    option_a: "A lion", option_b: "A horse", option_c: "A cheetah", option_d: "An ostrich", correct: "c" },
  { id: "ani_11", topic: "animals", difficulty: "child",
    question: "Which bird cannot fly?",
    option_a: "A parrot", option_b: "A sparrow", option_c: "An ostrich", option_d: "An eagle", correct: "c" },
  { id: "ani_12", topic: "animals", difficulty: "child",
    question: "What do bees make?",
    option_a: "Silk", option_b: "Honey", option_c: "Wax only", option_d: "Milk", correct: "b" },
  { id: "ani_13", topic: "animals", difficulty: "child",
    question: "Which animal is the largest on Earth?",
    option_a: "The African elephant", option_b: "The great white shark", option_c: "The blue whale", option_d: "The giraffe", correct: "c" },
  { id: "ani_14", topic: "animals", difficulty: "child",
    question: "What do you call a baby cat?",
    option_a: "A cub", option_b: "A pup", option_c: "A kitten", option_d: "A lamb", correct: "c" },
  { id: "ani_15", topic: "animals", difficulty: "child",
    question: "Which animal builds a dam to make a pond to live in?",
    option_a: "An otter", option_b: "A beaver", option_c: "A mole", option_d: "A platypus", correct: "b" },
  { id: "ani_16", topic: "animals", difficulty: "child",
    question: "What colour is a flamingo?",
    option_a: "White", option_b: "Yellow", option_c: "Pink", option_d: "Blue", correct: "c" },
  { id: "ani_17", topic: "animals", difficulty: "child",
    question: "Which animal has a very long nose called a trunk?",
    option_a: "A rhinoceros", option_b: "A tapir", option_c: "A hippopotamus", option_d: "An elephant", correct: "d" },
  { id: "ani_18", topic: "animals", difficulty: "child",
    question: "A group of lions is called a…",
    option_a: "Pack", option_b: "Herd", option_c: "Pride", option_d: "Flock", correct: "c" },
  { id: "ani_19", topic: "animals", difficulty: "child",
    question: "Which of these animals sleeps through winter (hibernates)?",
    option_a: "A rabbit", option_b: "A bear", option_c: "A cat", option_d: "A horse", correct: "b" },
  { id: "ani_20", topic: "animals", difficulty: "child",
    question: "Where do fish breathe using?",
    option_a: "Their nose", option_b: "Their skin", option_c: "Their gills", option_d: "Their fins", correct: "c" },

  // ─── Colours & Nature (20) ───────────────────────────────────────────
  { id: "nat_01", topic: "nature", difficulty: "child",
    question: "What colours appear in a rainbow? Pick the correct list.",
    option_a: "Red, orange, yellow, green, blue, indigo, violet", option_b: "Red, pink, yellow, green, blue, purple, brown", option_c: "Red, orange, yellow, green, teal, blue, purple", option_d: "Red, yellow, green, blue, white, grey, black", correct: "a" },
  { id: "nat_02", topic: "nature", difficulty: "child",
    question: "In which season do most trees lose their leaves?",
    option_a: "Spring", option_b: "Summer", option_c: "Autumn", option_d: "Winter", correct: "c" },
  { id: "nat_03", topic: "nature", difficulty: "child",
    question: "What does a seed need to start growing?",
    option_a: "Sunlight and salt", option_b: "Water, warmth, and soil (or compost)", option_c: "Ice and wind", option_d: "Sand and moonlight", correct: "b" },
  { id: "nat_04", topic: "nature", difficulty: "child",
    question: "What is the centre of our solar system?",
    option_a: "The Moon", option_b: "The Earth", option_c: "Jupiter", option_d: "The Sun", correct: "d" },
  { id: "nat_05", topic: "nature", difficulty: "child",
    question: "What colour do leaves turn to make food from sunlight?",
    option_a: "Red", option_b: "Brown", option_c: "Green (because of chlorophyll)", option_d: "Yellow", correct: "c" },
  { id: "nat_06", topic: "nature", difficulty: "child",
    question: "What is rain water called before it falls — when it is up in the sky?",
    option_a: "Fog", option_b: "A cloud", option_c: "Dew", option_d: "Mist", correct: "b" },
  { id: "nat_07", topic: "nature", difficulty: "child",
    question: "How many planets are in our solar system?",
    option_a: "7", option_b: "8", option_c: "9", option_d: "10", correct: "b" },
  { id: "nat_08", topic: "nature", difficulty: "child",
    question: "What is frozen water called?",
    option_a: "Steam", option_b: "Ice", option_c: "Frost only", option_d: "Hail only", correct: "b" },
  { id: "nat_09", topic: "nature", difficulty: "child",
    question: "Which season comes after winter?",
    option_a: "Autumn", option_b: "Summer", option_c: "Spring", option_d: "Another winter", correct: "c" },
  { id: "nat_10", topic: "nature", difficulty: "child",
    question: "What do we call the part of a flower that is brightly coloured to attract bees?",
    option_a: "The stem", option_b: "The root", option_c: "The petal", option_d: "The leaf", correct: "c" },
  { id: "nat_11", topic: "nature", difficulty: "child",
    question: "What is the name of our planet?",
    option_a: "Mars", option_b: "Venus", option_c: "Jupiter", option_d: "Earth", correct: "d" },
  { id: "nat_12", topic: "nature", difficulty: "child",
    question: "What shape is a snowflake?",
    option_a: "Round", option_b: "Six-sided (hexagonal)", option_c: "Square", option_d: "Triangle", correct: "b" },
  { id: "nat_13", topic: "nature", difficulty: "child",
    question: "What do plants use sunlight to make?",
    option_a: "Water", option_b: "Soil", option_c: "Food (through photosynthesis)", option_d: "Oxygen only", correct: "c" },
  { id: "nat_14", topic: "nature", difficulty: "child",
    question: "Which colour is made by mixing red and blue?",
    option_a: "Orange", option_b: "Green", option_c: "Yellow", option_d: "Purple", correct: "d" },
  { id: "nat_15", topic: "nature", difficulty: "child",
    question: "What falls from the sky in a thunderstorm?",
    option_a: "Snow", option_b: "Hail or rain", option_c: "Mud", option_d: "Leaves", correct: "b" },
  { id: "nat_16", topic: "nature", difficulty: "child",
    question: "A caterpillar wraps itself in a silk case to transform. What is that case called?",
    option_a: "A shell", option_b: "A cocoon or chrysalis", option_c: "A nest", option_d: "A pod", correct: "b" },
  { id: "nat_17", topic: "nature", difficulty: "child",
    question: "Which is hotter — the Sun or the Moon?",
    option_a: "They are both the same temperature", option_b: "The Moon", option_c: "The Sun", option_d: "It depends on the season", correct: "c" },
  { id: "nat_18", topic: "nature", difficulty: "child",
    question: "What do you call the sound thunder makes during a storm?",
    option_a: "A clap or rumble of thunder", option_b: "Lightning crack", option_c: "A sky boom", option_d: "A cloud burst", correct: "a" },
  { id: "nat_19", topic: "nature", difficulty: "child",
    question: "What colour is the sky on a clear sunny day?",
    option_a: "White", option_b: "Grey", option_c: "Blue", option_d: "Purple", correct: "c" },
  { id: "nat_20", topic: "nature", difficulty: "child",
    question: "What do you call the natural home where an animal lives?",
    option_a: "A garden", option_b: "A habitat", option_c: "A territory", option_d: "A burrow (for every animal)", correct: "b" },

  // ─── Fairy Tales & Stories (20) ──────────────────────────────────────
  { id: "fts_01", topic: "fairytales", difficulty: "child",
    question: "In 'Goldilocks and the Three Bears', whose porridge was 'just right'?",
    option_a: "Daddy Bear's", option_b: "Mummy Bear's", option_c: "Baby Bear's", option_d: "Goldilocks made her own", correct: "c" },
  { id: "fts_02", topic: "fairytales", difficulty: "child",
    question: "What does Cinderella leave behind at the ball when she runs away at midnight?",
    option_a: "Her handbag", option_b: "Her glass slipper", option_c: "Her tiara", option_d: "Her glove", correct: "b" },
  { id: "fts_03", topic: "fairytales", difficulty: "child",
    question: "In 'Jack and the Beanstalk', what does Jack trade for magic beans?",
    option_a: "His bicycle", option_b: "His shoes", option_c: "The family cow", option_d: "A golden egg", correct: "c" },
  { id: "fts_04", topic: "fairytales", difficulty: "child",
    question: "What is the name of the fairy in 'Peter Pan'?",
    option_a: "Pixie", option_b: "Tinker Bell", option_c: "Rosebud", option_d: "Glitter", correct: "b" },
  { id: "fts_05", topic: "fairytales", difficulty: "child",
    question: "In 'Snow White', what does the Evil Queen ask her magic mirror every day?",
    option_a: "How to make a potion", option_b: "Who is the fairest of them all?", option_c: "Where is Snow White hiding?", option_d: "How to find the dwarfs", correct: "b" },
  { id: "fts_06", topic: "fairytales", difficulty: "child",
    question: "How many dwarfs does Snow White live with?",
    option_a: "Five", option_b: "Six", option_c: "Eight", option_d: "Seven", correct: "d" },
  { id: "fts_07", topic: "fairytales", difficulty: "child",
    question: "In 'The Three Little Pigs', what does the wolf huff and puff to try to do?",
    option_a: "Make it rain", option_b: "Blow the houses down", option_c: "Scare the pigs away", option_d: "Climb over the fence", correct: "b" },
  { id: "fts_08", topic: "fairytales", difficulty: "child",
    question: "In 'Sleeping Beauty', what makes the princess fall into a deep sleep?",
    option_a: "A poisoned apple", option_b: "A magic mirror", option_c: "A spinning wheel's spindle prick", option_d: "A witch's spell involving a flower", correct: "c" },
  { id: "fts_09", topic: "fairytales", difficulty: "child",
    question: "What is Pinocchio famous for?",
    option_a: "His red hat", option_b: "His nose growing when he tells a lie", option_c: "His magic wand", option_d: "His dancing shoes", correct: "b" },
  { id: "fts_10", topic: "fairytales", difficulty: "child",
    question: "In 'Hansel and Gretel', what is the witch's house made of?",
    option_a: "Straw", option_b: "Bricks", option_c: "Gingerbread and sweets", option_d: "Wood and leaves", correct: "c" },
  { id: "fts_11", topic: "fairytales", difficulty: "child",
    question: "In 'The Ugly Duckling', what does the ugly duckling grow up to become?",
    option_a: "A beautiful swan", option_b: "A proud peacock", option_c: "A colourful parrot", option_d: "A graceful flamingo", correct: "a" },
  { id: "fts_12", topic: "fairytales", difficulty: "child",
    question: "What does Rumpelstiltskin want in exchange for spinning straw into gold?",
    option_a: "The queen's crown", option_b: "Her ring", option_c: "Her firstborn child", option_d: "A bag of gold coins", correct: "c" },
  { id: "fts_13", topic: "fairytales", difficulty: "child",
    question: "In 'Little Red Riding Hood', who is disguised as Grandma in bed?",
    option_a: "A fox", option_b: "A bear", option_c: "The woodsman", option_d: "The Big Bad Wolf", correct: "d" },
  { id: "fts_14", topic: "fairytales", difficulty: "child",
    question: "Aladdin finds a magic lamp in a cave. What comes out when he rubs the lamp?",
    option_a: "A fairy godmother", option_b: "A dragon", option_c: "A genie", option_d: "A princess", correct: "c" },
  { id: "fts_15", topic: "fairytales", difficulty: "child",
    question: "In the original fairy tale, The Little Mermaid wants to live on land. What does she give up to get legs?",
    option_a: "Her tail", option_b: "Her beautiful voice", option_c: "Her memories", option_d: "Her best friend", correct: "b" },
  { id: "fts_16", topic: "fairytales", difficulty: "child",
    question: "What breaks the spell on the Beast in 'Beauty and the Beast'?",
    option_a: "A magic potion", option_b: "A kiss from the prince", option_c: "True love — Belle says she loves him", option_d: "The enchanted rose fully blooming", correct: "c" },
  { id: "fts_17", topic: "fairytales", difficulty: "child",
    question: "In 'Puss in Boots', the cat helps his owner seem rich and powerful. What gift did the owner receive from his father?",
    option_a: "A horse", option_b: "A bag of money", option_c: "A magical sword", option_d: "A cat (Puss)", correct: "d" },
  { id: "fts_18", topic: "fairytales", difficulty: "child",
    question: "Alice falls into Wonderland by following which animal down a rabbit hole?",
    option_a: "A white cat", option_b: "A white rabbit with a pocket watch", option_c: "A talking mouse", option_d: "A blue caterpillar", correct: "b" },
  { id: "fts_19", topic: "fairytales", difficulty: "child",
    question: "In 'The Wizard of Oz', Dorothy wants to go home. What does she tap together to get there?",
    option_a: "Her blue shoes", option_b: "Her silver shoes (ruby slippers in the film)", option_c: "Her hands", option_d: "A magic wand", correct: "b" },
  { id: "fts_20", topic: "fairytales", difficulty: "child",
    question: "In 'Rapunzel', how does the prince (or witch) climb up to the tower?",
    option_a: "Using a magic ladder", option_b: "By climbing a vine", option_c: "By climbing Rapunzel's long hair", option_d: "Using a magic carpet", correct: "c" },
];
